[package]
name = "macro_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
proc-macro2 = "1.0.81"
quote = "1.0.36"
syn = "2.0.59"

[lints]
workspace = true
