[package]
name = "macro_core_impl"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
proc-macro2 = "1.0.79"
proc-macro-error = "1.0.4"
quote = "1.0.36"
syn = { version = "2.0.59", features = ["full"] }
